### ISSUE TITLE
2 out of 4 BsonObject constructors throws java.io.EOFException

### ISSUE THREAD

**Issue by kkulak** [Tesco/mewbase#144]
Hi guys,

2 out of 4 BsonObject constructors seems to be broken, I've managed to reproduce the errors below:

```
package io.mewbase.bson;

import io.vertx.core.buffer.Buffer;
import org.junit.Test;

public class BsonObjectTest {

    @Test
    public void shouldInstantiateBsonObjectFromBuffer() {
        // given
        final Buffer buffer = Buffer.buffer("{\"event_type\":\"manually_typed_address_merged\"}");

        // when
        new BsonObject(buffer);

        // then
        // no exception thrown
    }

    @Test
    public void shouldInstantiateBsonObjectFromRawBytes() {
        // given
        final byte[] bytes = "{\"event_type\":\"manually_typed_address_merged\"}".getBytes();

        // when
        new BsonObject(bytes);

        // then
        // no exception thrown
    }

}
```

Output:
```
java.lang.RuntimeException: java.io.EOFException

	at io.mewbase.bson.Bson.decodeValue(Bson.java:70)
	at io.mewbase.bson.BsonObject.fromBson(BsonObject.java:892)
	at io.mewbase.bson.BsonObject.<init>(BsonObject.java:56)
	at io.mewbase.bson.BsonObjectTest.shouldInstantiateBsonObjectFromBuffer(BsonObjectTest.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:237)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.EOFException
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUnsignedByte(LittleEndianInputStream.java:114)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readByte(LittleEndianInputStream.java:107)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUTF(LittleEndianInputStream.java:257)
	at de.undercouch.bson4jackson.io.LittleEndianInputStream.readUTF(LittleEndianInputStream.java:227)
	at de.undercouch.bson4jackson.BsonParser.readCString(BsonParser.java:551)
	at de.undercouch.bson4jackson.BsonParser.nextToken(BsonParser.java:281)
	at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:655)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:471)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:341)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3807)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2867)
	at io.mewbase.bson.Bson.decodeValue(Bson.java:68)
	... 25 more
```

Can you pls check what's wrong? Thanks!

Cheers,
Kamil

**Comment by NigeWarren** [comment]
Thanks Kamil - Yep Ill take a look and update here as and when - thanks for posting the bug - Nige

**Comment by NigeWarren** [comment]
Hi @kkulak @kings13y 

I went back and check the Documentation here ..

https://github.com/Tesco/mewbase/blob/master/src/main/java/io/mewbase/bson/BsonObject.java#L56

And in both cases the intent of the buffer method is to convert raw bytes of encoded BSON not JSON which would be the natural context for this conversion, in the same way the JsonObject conversion is from bytes of a text Json encoding.

The correct conversion is from a JsonObject to a BsonObject as in ...

https://github.com/Tesco/mewbase/blob/master/src/main/java/io/mewbase/bson/BsonObject.java#L91

So I have changed the none the less useful tests to 

    // answering #144
    @Test
    public void shouldInstantiateBsonObjectfromJsonObject() throws IOException {
        final String key = "event_type";
        final String value = "manually_typed_address_merged";
        final String jsonStr = "{\""+key+"\":\""+value+"\"}";
        final JsonObject jsonObject = new JsonObject(jsonStr);
        final BsonObject bsonObject = new BsonObject(jsonObject);
        assertNotNull(bsonObject);
        assertEquals(bsonObject.getString(key),value);
    }

I guess the rule of thumb is that we should always encode Json as a JsonObject before the Bson conversion.
